const miasta = [
  "Bolesławiec",
"Nowogrodziec",
"Bielawa",
"Dzierżoniów",
"Niemcza",
"Pieszyce",
"Piława Górna",
"Głogów",
"Góra",
"Wąsosz",
"Bolków",
"Jawor",
"Jelenia Góra",
"Kamienna Góra",
"Lubawka",
"Karpacz",
"Kowary",
"Piechowice",
"Szklarska Poręba",
"Bystrzyca Kłodzka",
"Duszniki-Zdrój",
"Kłodzko",
"Kudowa-Zdrój",
"Lądek-Zdrój",
"Międzylesie",
"Nowa Ruda",
"Polanica-Zdrój",
"Radków",
"Stronie Śląskie",
"Szczytna",
"Legnica",
"Chojnów",
"Prochowice",
"Leśna",
"Lubań",
"Olszyna",
"Świeradów-Zdrój",
"Lubin",
"Ścinawa",
"Gryfów Śląski",
"Lubomierz",
"Lwówek Śląski",
"Mirsk",
"Wleń",
"Milicz",
"Bierutów",
"Międzybórz",
"Oleśnica",
"Syców",
"Twardogóra",
"Jelcz-Laskowice",
"Oława",
"Chocianów",
"Polkowice",
"Przemków",
"Strzelin",
"Wiązów",
"Miękinia",
"Środa Śląska",
"Jaworzyna Śląska",
"Strzegom",
"Świdnica",
"Świebodzice",
"Żarów",
"Oborniki Śląskie",
"Prusice",
"Trzebnica",
"Żmigród",
"Wałbrzych",
"Boguszów-Gorce",
"Głuszyca",
"Jedlina-Zdrój",
"Mieroszów",
"Szczawno-Zdrój",
"Brzeg Dolny",
"Wołów",
"Wrocław",
"Kąty Wrocławskie",
"Siechnice",
"Sobótka",
"Bardo",
"Kamieniec Ząbkowicki",
"Ząbkowice Śląskie",
"Ziębice",
"Złoty Stok",
"Bogatynia",
"Pieńsk",
"Węgliniec",
"Zawidów",
"Zgorzelec",
"Świerzawa",
"Wojcieszów",
"Złotoryja",
"Aleksandrów Kujawski",
"Ciechocinek",
"Nieszawa",
"Brodnica",
"Górzno",
"Jabłonowo Pomorskie",
"Koronowo",
"Solec Kujawski",
"Bydgoszcz",
"Chełmno",
"Golub-Dobrzyń",
"Kowalewo Pomorskie",
"Grudziądz",
"Łasin",
"Radzyń Chełmiński",
"Gniewkowo",
"Inowrocław",
"Janikowo",
"Kruszwica",
"Pakość",
"Bobrowniki",
"Dobrzyń nad Wisłą",
"Kikół",
"Lipno",
"Skępe",
"Mogilno",
"Strzelno",
"Kcynia",
"Mrocza",
"Nakło nad Notecią",
"Szubin",
"Piotrków Kujawski",
"Radziejów",
"Rypin",
"Kamień Krajeński",
"Sępólno Krajeńskie",
"Więcbork",
"Nowe",
"Pruszcz",
"Świecie",
"Toruń",
"Chełmża",
"Tuchola",
"Wąbrzeźno",
"Włocławek",
"Brześć Kujawski",
"Chodecz",
"Izbica Kujawska",
"Kowal",
"Lubień Kujawski",
"Lubraniec",
"Barcin",
"Gąsawa",
"Janowiec Wielkopolski",
"Łabiszyn",
"Żnin",
"Międzyrzec Podlaski",
"Piszczac",
"Terespol",
"Biała Podlaska",
"Biłgoraj",
"Frampol",
"Goraj",
"Józefów",
"Tarnogród",
"Turobin",
"Chełm",
"Rejowiec",
"Rejowiec Fabryczny",
"Siedliszcze",
"Hrubieszów",
"Janów Lubelski",
"Modliborzyce",
"Izbica",
"Krasnystaw",
"Annopol",
"Kraśnik",
"Urzędów",
"Kamionka",
"Kock",
"Lubartów",
"Ostrów Lubelski",
"Bełżyce",
"Bychawa",
"Lublin",
"Łęczna",
"Łuków",
"Stoczek Łukowski",
"Józefów nad Wisłą",
"Opole Lubelskie",
"Poniatowa",
"Parczew",
"Kazimierz Dolny",
"Nałęczów",
"Puławy",
"Czemierniki",
"Radzyń Podlaski",
"Dęblin",
"Ryki",
"Piaski",
"Świdnik",
"Lubycza Królewska",
"Łaszczów",
"Tomaszów Lubelski",
"Tyszowce",
"Włodawa",
"Krasnobród",
"Szczebrzeszyn",
"Zwierzyniec",
"Zamość",
"Kostrzyn nad Odrą",
"Witnica",
"Gorzów Wielkopolski",
"Gubin",
"Krosno Odrzańskie",
"Międzyrzecz",
"Skwierzyna",
"Trzciel",
"Bytom Odrzański",
"Kożuchów",
"Nowa Sól",
"Nowe Miasteczko",
"Otyń",
"Cybinka",
"Ośno Lubuskie",
"Rzepin",
"Słubice",
"Dobiegniew",
"Drezdenko",
"Strzelce Krajeńskie",
"Lubniewice",
"Sulęcin",
"Torzym",
"Świebodzin",
"Zbąszynek",
"Sława",
"Szlichtyngowa",
"Wschowa",
"Zielona Góra",
"Babimost",
"Czerwieńsk",
"Kargowa",
"Nowogród Bobrzański",
"Sulechów",
"Gozdnica",
"Iłowa",
"Małomice",
"Szprotawa",
"Żagań",
"Brody",
"Jasień",
"Lubsko",
"Łęknica",
"Żary",
"Bełchatów",
"Zelów",
"Brzeziny",
"Jeżów",
"Dąbrowice",
"Krośniewice",
"Kutno",
"Żychlin",
"Łask",
"Grabów",
"Łęczyca",
"Piątek",
"Kiernozia",
"Łowicz",
"Koluszki",
"Rzgów",
"Tuszyn",
"Łódź",
"Białaczów",
"Drzewica",
"Opoczno",
"Żarnów",
"Konstantynów Łódzki",
"Lutomiersk",
"Pabianice",
"Działoszyn",
"Pajęczno",
"Rozprza",
"Sulejów",
"Wolbórz",
"Piotrków Trybunalski",
"Poddębice",
"Uniejów",
"Kamieńsk",
"Przedbórz",
"Radomsko",
"Biała Rawska",
"Rawa Mazowiecka",
"Błaszki",
"Sieradz",
"Warta",
"Złoczew",
"Skierniewice",
"Bolimów",
"Inowłódz",
"Tomaszów Mazowiecki",
"Ujazd",
"Osjaków",
"Wieluń",
"Bolesławiec",
"Lututów",
"Wieruszów",
"Szadek",
"Zduńska Wola",
"Aleksandrów Łódzki",
"Głowno",
"Ozorków",
"Parzęczew",
"Stryków",
"Zgierz",
"Bochnia",
"Nowy Wiśnicz",
"Brzesko",
"Czchów",
"Alwernia",
"Chrzanów",
"Libiąż",
"Trzebinia",
"Dąbrowa Tarnowska",
"Szczucin",
"Biecz",
"Bobowa",
"Gorlice",
"Krzeszowice",
"Skała",
"Skawina",
"Słomniki",
"Świątniki Górne",
"Kraków",
"Limanowa",
"Mszana Dolna",
"Książ Wielki",
"Miechów",
"Dobczyce",
"Myślenice",
"Sułkowice",
"Grybów",
"Krynica-Zdrój",
"Muszyna",
"Piwniczna-Zdrój",
"Stary Sącz",
"Czarny Dunajec",
"Nowy Targ",
"Rabka-Zdrój",
"Szczawnica",
"Nowy Sącz",
"Bukowno",
"Olkusz",
"Wolbrom",
"Brzeszcze",
"Chełmek",
"Kęty",
"Oświęcim",
"Zator",
"Koszyce",
"Nowe Brzesko",
"Proszowice",
"Jordanów",
"Maków Podhalański",
"Sucha Beskidzka",
"Ciężkowice",
"Radłów",
"Ryglice",
"Tuchów",
"Wojnicz",
"Zakliczyn",
"Żabno",
"Tarnów",
"Zakopane",
"Andrychów",
"Kalwaria Zebrzydowska",
"Wadowice",
"Niepołomice",
"Wieliczka",
"Białobrzegi",
"Wyśmierzyce",
"Ciechanów",
"Glinojeck",
"Garwolin",
"Łaskarzew",
"Maciejowice",
"Pilawa",
"Żelechów",
"Gostynin",
"Sanniki",
"Grodzisk Mazowiecki",
"Milanówek",
"Podkowa Leśna",
"Grójec",
"Mogielnica",
"Nowe Miasto nad Pilicą",
"Warka",
"Głowaczów",
"Kozienice",
"Magnuszew",
"Legionowo",
"Serock",
"Ciepielów",
"Lipsko",
"Sienno",
"Solec nad Wisłą",
"Łosice",
"Maków Mazowiecki",
"Różan",
"Cegłów",
"Dobre",
"Halinów",
"Kałuszyn",
"Latowicz",
"Mińsk Mazowiecki",
"Mrozy",
"Siennica",
"Sulejówek",
"Mława",
"Nasielsk",
"Nowy Dwór Mazowiecki",
"Zakroczym",
"Myszyniec",
"Ostrołęka",
"Brok",
"Ostrów Mazowiecka",
"Józefów",
"Karczew",
"Osieck",
"Otwock",
"Góra Kalwaria",
"Konstancin-Jeziorna",
"Piaseczno",
"Tarczyn",
"Płock",
"Bodzanów",
"Drobin",
"Gąbin",
"Wyszogród",
"Czerwińsk nad Wisłą",
"Nowe Miasto",
"Płońsk",
"Raciąż",
"Sochocin",
"Brwinów",
"Piastów",
"Pruszków",
"Chorzele",
"Przasnysz",
"Gielniów",
"Odrzywół",
"Przysucha",
"Pułtusk",
"Radom",
"Iłża",
"Jedlnia-Letnisko",
"Pionki",
"Przytyk",
"Skaryszew",
"Siedlce",
"Mordy",
"Sierpc",
"Sochaczew",
"Kosów Lacki",
"Sokołów Podlaski",
"Jastrząb",
"Szydłowiec",
"Warszawa",
"Błonie",
"Łomianki",
"Ożarów Mazowiecki",
"Łochów",
"Węgrów",
"Jadów",
"Kobyłka",
"Marki",
"Radzymin",
"Tłuszcz",
"Wołomin",
"Ząbki",
"Zielonka",
"Wyszków",
"Zwoleń",
"Bieżuń",
"Lubowidz",
"Żuromin",
"Mszczonów",
"Wiskitki",
"Żyrardów",
"Brzeg",
"Grodków",
"Lewin Brzeski",
"Baborów",
"Głubczyce",
"Kietrz",
"Kędzierzyn-Koźle",
"Byczyna",
"Kluczbork",
"Wołczyn",
"Gogolin",
"Krapkowice",
"Strzeleczki",
"Zdzieszowice",
"Namysłów",
"Głuchołazy",
"Korfantów",
"Nysa",
"Otmuchów",
"Paczków",
"Dobrodzień",
"Gorzów Śląski",
"Olesno",
"Praszka",
"Opole",
"Niemodlin",
"Ozimek",
"Prószków",
"Tułowice",
"Biała",
"Głogówek",
"Prudnik",
"Kolonowskie",
"Leśnica",
"Strzelce Opolskie",
"Ujazd",
"Zawadzkie",
"Ustrzyki Dolne",
"Brzozów",
"Brzostek",
"Dębica",
"Pilzno",
"Jarosław",
"Pruchnik",
"Radymno",
"Jasło",
"Kołaczyce",
"Kolbuszowa",
"Krosno",
"Dukla",
"Iwonicz-Zdrój",
"Jedlicze",
"Rymanów",
"Lesko",
"Leżajsk",
"Nowa Sarzyna",
"Cieszanów",
"Lubaczów",
"Narol",
"Oleszyce",
"Łańcut",
"Mielec",
"Przecław",
"Radomyśl Wielki",
"Nisko",
"Rudnik nad Sanem",
"Ulanów",
"Bircza",
"Dubiecko",
"Przemyśl",
"Jawornik Polski",
"Kańczuga",
"Przeworsk",
"Sieniawa",
"Ropczyce",
"Sędziszów Małopolski",
"Błażowa",
"Boguchwała",
"Dynów",
"Głogów Małopolski",
"Sokołów Małopolski",
"Tyczyn",
"Rzeszów",
"Sanok",
"Zagórz",
"Stalowa Wola",
"Zaklików",
"Strzyżów",
"Tarnobrzeg",
"Baranów Sandomierski",
"Nowa Dęba",
"Augustów",
"Lipsk",
"Choroszcz",
"Czarna Białostocka",
"Łapy",
"Michałowo",
"Supraśl",
"Suraż",
"Tykocin",
"Wasilków",
"Zabłudów",
"Białystok",
"Bielsk Podlaski",
"Brańsk",
"Grajewo",
"Rajgród",
"Szczuczyn",
"Hajnówka",
"Kleszczele",
"Kolno",
"Stawiski",
"Łomża",
"Jedwabne",
"Nowogród",
"Goniądz",
"Knyszyn",
"Mońki",
"Sejny",
"Drohiczyn",
"Siemiatycze",
"Dąbrowa Białostocka",
"Krynki",
"Sokółka",
"Suchowola",
"Suwałki",
"Ciechanowiec",
"Czyżew",
"Szepietowo",
"Wysokie Mazowieckie",
"Zambrów",
"Bytów",
"Miastko",
"Brusy",
"Chojnice",
"Czersk",
"Czarne",
"Człuchów",
"Debrzno",
"Gdańsk",
"Pruszcz Gdański",
"Gdynia",
"Kartuzy",
"Żukowo",
"Kościerzyna",
"Kwidzyn",
"Prabuty",
"Lębork",
"Łeba",
"Malbork",
"Nowy Staw",
"Krynica Morska",
"Nowy Dwór Gdański",
"Hel",
"Jastarnia",
"Puck",
"Władysławowo",
"Słupsk",
"Kępice",
"Ustka",
"Sopot",
"Czarna Woda",
"Skarszewy",
"Skórcz",
"Starogard Gdański",
"Dzierzgoń",
"Sztum",
"Gniew",
"Pelplin",
"Tczew",
"Reda",
"Rumia",
"Wejherowo",
"Będzin",
"Czeladź",
"Siewierz",
"Sławków",
"Wojkowice",
"Czechowice-Dziedzice",
"Szczyrk",
"Wilamowice",
"Bielsko-Biała",
"Bieruń",
"Imielin",
"Lędziny",
"Bytom",
"Chorzów",
"Cieszyn",
"Skoczów",
"Strumień",
"Ustroń",
"Wisła",
"Częstochowa",
"Blachownia",
"Koniecpol",
"Olsztyn",
"Przyrów",
"Dąbrowa Górnicza",
"Gliwice",
"Knurów",
"Pyskowice",
"Sośnicowice",
"Toszek",
"Jastrzębie-Zdrój",
"Jaworzno",
"Katowice",
"Kłobuck",
"Krzepice",
"Lubliniec",
"Woźniki",
"Łaziska Górne",
"Mikołów",
"Orzesze",
"Mysłowice",
"Koziegłowy",
"Myszków",
"Żarki",
"Piekary Śląskie",
"Pszczyna",
"Krzanowice",
"Kuźnia Raciborska",
"Racibórz",
"Ruda Śląska",
"Czerwionka-Leszczyny",
"Rybnik",
"Siemianowice Śląskie",
"Sosnowiec",
"Świętochłowice",
"Kalety",
"Miasteczko Śląskie",
"Radzionków",
"Tarnowskie Góry",
"Tychy",
"Pszów",
"Radlin",
"Rydułtowy",
"Wodzisław Śląski",
"Zabrze",
"Łazy",
"Ogrodzieniec",
"Pilica",
"Poręba",
"Szczekociny",
"Włodowice",
"Zawiercie",
"Żory",
"Żywiec",
"Busko-Zdrój",
"Nowy Korczyn",
"Pacanów",
"Stopnica",
"Wiślica",
"Jędrzejów",
"Małogoszcz",
"Sędziszów",
"Wodzisław",
"Kazimierza Wielka",
"Opatowiec",
"Skalbmierz",
"Kielce",
"Bodzentyn",
"Chęciny",
"Chmielnik",
"Daleszyce",
"Łagów",
"Łopuszno",
"Morawica",
"Nowa Słupia",
"Piekoszów",
"Pierzchnica",
"Gowarczów",
"Końskie",
"Radoszyce",
"Stąporków",
"Iwaniska",
"Opatów",
"Ożarów",
"Ćmielów",
"Kunów",
"Ostrowiec Świętokrzyski",
"Działoszyce",
"Pińczów",
"Klimontów",
"Koprzywnica",
"Sandomierz",
"Zawichost",
"Skarżysko-Kamienna",
"Suchedniów",
"Starachowice",
"Wąchock",
"Bogoria",
"Oleśnica",
"Osiek",
"Połaniec",
"Staszów",
"Szydłów",
"Włoszczowa",
"Bartoszyce",
"Bisztynek",
"Górowo Iławeckie",
"Sępopol",
"Braniewo",
"Frombork",
"Pieniężno",
"Działdowo",
"Lidzbark",
"Elbląg",
"Młynary",
"Pasłęk",
"Tolkmicko",
"Ełk",
"Giżycko",
"Ryn",
"Gołdap",
"Iława",
"Kisielice",
"Lubawa",
"Susz",
"Zalewo",
"Kętrzyn",
"Korsze",
"Reszel",
"Lidzbark Warmiński",
"Orneta",
"Mikołajki",
"Mrągowo",
"Nidzica",
"Nowe Miasto Lubawskie",
"Olecko",
"Olsztyn",
"Barczewo",
"Biskupiec",
"Dobre Miasto",
"Jeziorany",
"Olsztynek",
"Miłakowo",
"Miłomłyn",
"Morąg",
"Ostróda",
"Biała Piska",
"Orzysz",
"Pisz",
"Ruciane-Nida",
"Pasym",
"Szczytno",
"Wielbark",
"Węgorzewo",
"Budzyń",
"Chodzież",
"Margonin",
"Szamocin",
"Czarnków",
"Krzyż Wielkopolski",
"Trzcianka",
"Wieleń",
"Czerniejewo",
"Gniezno",
"Kłecko",
"Trzemeszno",
"Witkowo",
"Borek Wielkopolski",
"Gostyń",
"Krobia",
"Pogorzela",
"Poniec",
"Grodzisk Wielkopolski",
"Rakoniewice",
"Wielichowo",
"Jaraczewo",
"Jarocin",
"Żerków",
"Koźminek",
"Opatówek",
"Stawiszyn",
"Kalisz",
"Kępno",
"Rychtal",
"Dąbie",
"Kłodawa",
"Koło",
"Przedecz",
"Konin",
"Golina",
"Kleczew",
"Rychwał",
"Sompolno",
"Ślesin",
"Czempiń",
"Kościan",
"Krzywiń",
"Śmigiel",
"Kobylin",
"Koźmin Wielkopolski",
"Krotoszyn",
"Sulmierzyce",
"Zduny",
"Osieczna",
"Rydzyna",
"Leszno",
"Międzychód",
"Sieraków",
"Lwówek",
"Nowy Tomyśl",
"Opalenica",
"Zbąszyń",
"Oborniki",
"Rogoźno",
"Nowe Skalmierzyce",
"Odolanów",
"Ostrów Wielkopolski",
"Raszków",
"Grabów nad Prosną",
"Mikstat",
"Ostrzeszów",
"Kaczory",
"Łobżenica",
"Miasteczko Krajeńskie",
"Piła",
"Ujście",
"Wyrzysk",
"Wysoka",
"Chocz",
"Dobrzyca",
"Pleszew",
"Poznań",
"Buk",
"Kostrzyn",
"Kórnik",
"Luboń",
"Mosina",
"Murowana Goślina",
"Pobiedziska",
"Puszczykowo",
"Stęszew",
"Swarzędz",
"Bojanowo",
"Jutrosin",
"Miejska Górka",
"Rawicz",
"Słupca",
"Zagórów",
"Obrzycko",
"Ostroróg",
"Pniewy",
"Szamotuły",
"Wronki",
"Środa Wielkopolska",
"Dolsk",
"Książ Wielkopolski",
"Śrem",
"Dobra",
"Tuliszków",
"Turek",
"Gołańcz",
"Mieścisko",
"Skoki",
"Wągrowiec",
"Wolsztyn",
"Miłosław",
"Nekla",
"Pyzdry",
"Września",
"Jastrowie",
"Krajenka",
"Okonek",
"Złotów",
"Białogard",
"Karlino",
"Tychowo",
"Choszczno",
"Drawno",
"Pełczyce",
"Recz",
"Czaplinek",
"Drawsko Pomorskie",
"Kalisz Pomorski",
"Złocieniec",
"Goleniów",
"Maszewo",
"Nowogard",
"Stepnica",
"Gryfice",
"Płoty",
"Trzebiatów",
"Cedynia",
"Chojna",
"Gryfino",
"Mieszkowice",
"Moryń",
"Trzcińsko-Zdrój",
"Dziwnów",
"Golczewo",
"Kamień Pomorski",
"Międzyzdroje",
"Wolin",
"Gościno",
"Kołobrzeg",
"Koszalin",
"Bobolice",
"Mielno",
"Polanów",
"Sianów",
"Dobra",
"Łobez",
"Resko",
"Węgorzyno",
"Barlinek",
"Dębno",
"Myślibórz",
"Nowe Warpno",
"Police",
"Lipiany",
"Pyrzyce",
"Darłowo",
"Sławno",
"Chociwel",
"Dobrzany",
"Ińsko",
"Stargard",
"Suchań",
"Szczecin",
"Barwice",
"Biały Bór",
"Borne Sulinowo",
"Szczecinek",
"Połczyn-Zdrój",
"Świdwin",
"Świnoujście",
"Człopa",
"Mirosławiec",
"Tuczno",
"Wałcz"
]

export default miasta = [
  {label: "Bolesławiec", value: "Bolesławiec"},
  {label: "Nowogrodziec", value: "Nowogrodziec"},
  {label: "Bielawa", value: "Bielawa"},
  {label: "Dzierżoniów", value: "Dzierżoniów"},
  {label: "Niemcza", value: "Niemcza"},
  {label: "Pieszyce", value: "Pieszyce"},
  {label: "Piława Górna", value: "Piława Górna"},
  {label: "Głogów", value: "Głogów"},
  {label: "Góra", value: "Góra"},
  {label: "Wąsosz", value: "Wąsosz"},
  {label: "Bolków", value: "Bolków"},
  {label: "Jawor", value: "Jawor"},
  {label: "Jelenia Góra", value: "Jelenia Góra"},
  {label: "Kamienna Góra", value: "Kamienna Góra"},
  {label: "Lubawka", value: "Lubawka"},
  {label: "Karpacz", value: "Karpacz"},
  {label: "Kowary", value: "Kowary"},
  {label: "Piechowice", value: "Piechowice"},
  {label: "Szklarska Poręba", value: "Szklarska Poręba"},
  {label: "Bystrzyca Kłodzka", value: "Bystrzyca Kłodzka"},
  {label: "Duszniki-Zdrój", value: "Duszniki-Zdrój"},
  {label: "Kłodzko", value: "Kłodzko"},
  {label: "Kudowa-Zdrój", value: "Kudowa-Zdrój"},
  {label: "Lądek-Zdrój", value: "Lądek-Zdrój"},
  {label: "Międzylesie", value: "Międzylesie"},
  {label: "Nowa Ruda", value: "Nowa Ruda"},
  {label: "Polanica-Zdrój", value: "Polanica-Zdrój"},
  {label: "Radków", value: "Radków"},
  {label: "Stronie Śląskie", value: "Stronie Śląskie"},
  {label: "Szczytna", value: "Szczytna"},
  {label: "Legnica", value: "Legnica"},
  {label: "Chojnów", value: "Chojnów"},
  {label: "Prochowice", value: "Prochowice"},
  {label: "Leśna", value: "Leśna"},
  {label: "Lubań", value: "Lubań"},
  {label: "Olszyna", value: "Olszyna"},
  {label: "Świeradów-Zdrój", value: "Świeradów-Zdrój"},
  {label: "Lubin", value: "Lubin"},
  {label: "Ścinawa", value: "Ścinawa"},
  {label: "Gryfów Śląski", value: "Gryfów Śląski"},
  {label: "Lubomierz", value: "Lubomierz"},
  {label: "Lwówek Śląski", value: "Lwówek Śląski"},
  {label: "Mirsk", value: "Mirsk"},
  {label: "Wleń", value: "Wleń"},
  {label: "Milicz", value: "Milicz"},
  {label: "Bierutów", value: "Bierutów"},
  {label: "Międzybórz", value: "Międzybórz"},
  {label: "Oleśnica", value: "Oleśnica"},
  {label: "Syców", value: "Syców"},
  {label: "Twardogóra", value: "Twardogóra"},
  {label: "Jelcz-Laskowice", value: "Jelcz-Laskowice"},
  {label: "Oława", value: "Oława"},
  {label: "Chocianów", value: "Chocianów"},
  {label: "Polkowice", value: "Polkowice"},
  {label: "Przemków", value: "Przemków"},
  {label: "Strzelin", value: "Strzelin"},
  {label: "Wiązów", value: "Wiązów"},
  {label: "Miękinia", value: "Miękinia"},
  {label: "Środa Śląska", value: "Środa Śląska"},
  {label: "Jaworzyna Śląska", value: "Jaworzyna Śląska"},
  {label: "Strzegom", value: "Strzegom"},
  {label: "Świdnica", value: "Świdnica"},
  {label: "Świebodzice", value: "Świebodzice"},
  {label: "Żarów", value: "Żarów"},
  {label: "Oborniki Śląskie", value: "Oborniki Śląskie"},
  {label: "Prusice", value: "Prusice"},
  {label: "Trzebnica", value: "Trzebnica"},
  {label: "Żmigród", value: "Żmigród"},
  {label: "Wałbrzych", value: "Wałbrzych"},
  {label: "Boguszów-Gorce", value: "Boguszów-Gorce"},
  {label: "Głuszyca", value: "Głuszyca"},
  {label: "Jedlina-Zdrój", value: "Jedlina-Zdrój"},
  {label: "Mieroszów", value: "Mieroszów"},
  {label: "Szczawno-Zdrój", value: "Szczawno-Zdrój"},
  {label: "Brzeg Dolny", value: "Brzeg Dolny"},
  {label: "Wołów", value: "Wołów"},
  {label: "Wrocław", value: "Wrocław"},
  {label: "Kąty Wrocławskie", value: "Kąty Wrocławskie"},
  {label: "Siechnice", value: "Siechnice"},
  {label: "Sobótka", value: "Sobótka"},
  {label: "Bardo", value: "Bardo"},
  {label: "Kamieniec Ząbkowicki", value: "Kamieniec Ząbkowicki"},
  {label: "Ząbkowice Śląskie", value: "Ząbkowice Śląskie"},
  {label: "Ziębice", value: "Ziębice"},
  {label: "Złoty Stok", value: "Złoty Stok"},
  {label: "Bogatynia", value: "Bogatynia"},
  {label: "Pieńsk", value: "Pieńsk"},
  {label: "Węgliniec", value: "Węgliniec"},
  {label: "Zawidów", value: "Zawidów"},
  {label: "Zgorzelec", value: "Zgorzelec"},
  {label: "Świerzawa", value: "Świerzawa"},
  {label: "Wojcieszów", value: "Wojcieszów"},
  {label: "Złotoryja", value: "Złotoryja"},
  {label: "Aleksandrów Kujawski", value: "Aleksandrów Kujawski"},
  {label: "Ciechocinek", value: "Ciechocinek"},
  {label: "Nieszawa", value: "Nieszawa"},
  {label: "Brodnica", value: "Brodnica"},
  {label: "Górzno", value: "Górzno"},
  {label: "Jabłonowo Pomorskie", value: "Jabłonowo Pomorskie"},
  {label: "Koronowo", value: "Koronowo"},
  {label: "Solec Kujawski", value: "Solec Kujawski"},
  {label: "Bydgoszcz", value: "Bydgoszcz"},
  {label: "Chełmno", value: "Chełmno"},
  {label: "Golub-Dobrzyń", value: "Golub-Dobrzyń"},
  {label: "Kowalewo Pomorskie", value: "Kowalewo Pomorskie"},
  {label: "Grudziądz", value: "Grudziądz"},
  {label: "Łasin", value: "Łasin"},
  {label: "Radzyń Chełmiński", value: "Radzyń Chełmiński"},
  {label: "Gniewkowo", value: "Gniewkowo"},
  {label: "Inowrocław", value: "Inowrocław"},
  {label: "Janikowo", value: "Janikowo"},
  {label: "Kruszwica", value: "Kruszwica"},
  {label: "Pakość", value: "Pakość"},
  {label: "Bobrowniki", value: "Bobrowniki"},
  {label: "Dobrzyń nad Wisłą", value: "Dobrzyń nad Wisłą"},
  {label: "Kikół", value: "Kikół"},
  {label: "Lipno", value: "Lipno"},
  {label: "Skępe", value: "Skępe"},
  {label: "Mogilno", value: "Mogilno"},
  {label: "Strzelno", value: "Strzelno"},
  {label: "Kcynia", value: "Kcynia"},
  {label: "Mrocza", value: "Mrocza"},
  {label: "Nakło nad Notecią", value: "Nakło nad Notecią"},
  {label: "Szubin", value: "Szubin"},
  {label: "Piotrków Kujawski", value: "Piotrków Kujawski"},
  {label: "Radziejów", value: "Radziejów"},
  {label: "Rypin", value: "Rypin"},
  {label: "Kamień Krajeński", value: "Kamień Krajeński"},
  {label: "Sępólno Krajeńskie", value: "Sępólno Krajeńskie"},
  {label: "Więcbork", value: "Więcbork"},
  {label: "Nowe", value: "Nowe"},
  {label: "Pruszcz", value: "Pruszcz"},
  {label: "Świecie", value: "Świecie"},
  {label: "Toruń", value: "Toruń"},
  {label: "Chełmża", value: "Chełmża"},
  {label: "Tuchola", value: "Tuchola"},
  {label: "Wąbrzeźno", value: "Wąbrzeźno"},
  {label: "Włocławek", value: "Włocławek"},
  {label: "Brześć Kujawski", value: "Brześć Kujawski"},
  {label: "Chodecz", value: "Chodecz"},
  {label: "Izbica Kujawska", value: "Izbica Kujawska"},
  {label: "Kowal", value: "Kowal"},
  {label: "Lubień Kujawski", value: "Lubień Kujawski"},
  {label: "Lubraniec", value: "Lubraniec"},
  {label: "Barcin", value: "Barcin"},
  {label: "Gąsawa", value: "Gąsawa"},
  {label: "Janowiec Wielkopolski", value: "Janowiec Wielkopolski"},
  {label: "Łabiszyn", value: "Łabiszyn"},
  {label: "Żnin", value: "Żnin"},
  {label: "Międzyrzec Podlaski", value: "Międzyrzec Podlaski"},
  {label: "Piszczac", value: "Piszczac"},
  {label: "Terespol", value: "Terespol"},
  {label: "Biała Podlaska", value: "Biała Podlaska"},
  {label: "Biłgoraj", value: "Biłgoraj"},
  {label: "Frampol", value: "Frampol"},
  {label: "Goraj", value: "Goraj"},
  {label: "Józefów", value: "Józefów"},
  {label: "Tarnogród", value: "Tarnogród"},
  {label: "Turobin", value: "Turobin"},
  {label: "Chełm", value: "Chełm"},
  {label: "Rejowiec", value: "Rejowiec"},
  {label: "Rejowiec Fabryczny", value: "Rejowiec Fabryczny"},
  {label: "Siedliszcze", value: "Siedliszcze"},
  {label: "Hrubieszów", value: "Hrubieszów"},
  {label: "Janów Lubelski", value: "Janów Lubelski"},
  {label: "Modliborzyce", value: "Modliborzyce"},
  {label: "Izbica", value: "Izbica"},
  {label: "Krasnystaw", value: "Krasnystaw"},
  {label: "Annopol", value: "Annopol"},
  {label: "Kraśnik", value: "Kraśnik"},
  {label: "Urzędów", value: "Urzędów"},
  {label: "Kamionka", value: "Kamionka"},
  {label: "Kock", value: "Kock"},
  {label: "Lubartów", value: "Lubartów"},
  {label: "Ostrów Lubelski", value: "Ostrów Lubelski"},
  {label: "Bełżyce", value: "Bełżyce"},
  {label: "Bychawa", value: "Bychawa"},
  {label: "Lublin", value: "Lublin"},
  {label: "Łęczna", value: "Łęczna"},
  {label: "Łuków", value: "Łuków"},
  {label: "Stoczek Łukowski", value: "Stoczek Łukowski"},
  {label: "Józefów nad Wisłą", value: "Józefów nad Wisłą"},
  {label: "Opole Lubelskie", value: "Opole Lubelskie"},
  {label: "Poniatowa", value: "Poniatowa"},
  {label: "Parczew", value: "Parczew"},
  {label: "Kazimierz Dolny", value: "Kazimierz Dolny"},
  {label: "Nałęczów", value: "Nałęczów"},
  {label: "Puławy", value: "Puławy"},
  {label: "Czemierniki", value: "Czemierniki"},
  {label: "Radzyń Podlaski", value: "Radzyń Podlaski"},
  {label: "Dęblin", value: "Dęblin"},
  {label: "Ryki", value: "Ryki"},
  {label: "Piaski", value: "Piaski"},
  {label: "Świdnik", value: "Świdnik"},
  {label: "Lubycza Królewska", value: "Lubycza Królewska"},
  {label: "Łaszczów", value: "Łaszczów"},
  {label: "Tomaszów Lubelski", value: "Tomaszów Lubelski"},
  {label: "Tyszowce", value: "Tyszowce"},
  {label: "Włodawa", value: "Włodawa"},
  {label: "Krasnobród", value: "Krasnobród"},
  {label: "Szczebrzeszyn", value: "Szczebrzeszyn"},
  {label: "Zwierzyniec", value: "Zwierzyniec"},
  {label: "Zamość", value: "Zamość"},
  {label: "Kostrzyn nad Odrą", value: "Kostrzyn nad Odrą"},
  {label: "Witnica", value: "Witnica"},
  {label: "Gorzów Wielkopolski", value: "Gorzów Wielkopolski"},
  {label: "Gubin", value: "Gubin"},
  {label: "Krosno Odrzańskie", value: "Krosno Odrzańskie"},
  {label: "Międzyrzecz", value: "Międzyrzecz"},
  {label: "Skwierzyna", value: "Skwierzyna"},
  {label: "Trzciel", value: "Trzciel"},
  {label: "Bytom Odrzański", value: "Bytom Odrzański"},
  {label: "Kożuchów", value: "Kożuchów"},
  {label: "Nowa Sól", value: "Nowa Sól"},
  {label: "Nowe Miasteczko", value: "Nowe Miasteczko"},
  {label: "Otyń", value: "Otyń"},
  {label: "Cybinka", value: "Cybinka"},
  {label: "Ośno Lubuskie", value: "Ośno Lubuskie"},
  {label: "Rzepin", value: "Rzepin"},
  {label: "Słubice", value: "Słubice"},
  {label: "Dobiegniew", value: "Dobiegniew"},
  {label: "Drezdenko", value: "Drezdenko"},
  {label: "Strzelce Krajeńskie", value: "Strzelce Krajeńskie"},
  {label: "Lubniewice", value: "Lubniewice"},
  {label: "Sulęcin", value: "Sulęcin"},
  {label: "Torzym", value: "Torzym"},
  {label: "Świebodzin", value: "Świebodzin"},
  {label: "Zbąszynek", value: "Zbąszynek"},
  {label: "Sława", value: "Sława"},
  {label: "Szlichtyngowa", value: "Szlichtyngowa"},
  {label: "Wschowa", value: "Wschowa"},
  {label: "Zielona Góra", value: "Zielona Góra"},
  {label: "Babimost", value: "Babimost"},
  {label: "Czerwieńsk", value: "Czerwieńsk"},
  {label: "Kargowa", value: "Kargowa"},
  {label: "Nowogród Bobrzański", value: "Nowogród Bobrzański"},
  {label: "Sulechów", value: "Sulechów"},
  {label: "Gozdnica", value: "Gozdnica"},
  {label: "Iłowa", value: "Iłowa"},
  {label: "Małomice", value: "Małomice"},
  {label: "Szprotawa", value: "Szprotawa"},
  {label: "Żagań", value: "Żagań"},
  {label: "Brody", value: "Brody"},
  {label: "Jasień", value: "Jasień"},
  {label: "Lubsko", value: "Lubsko"},
  {label: "Łęknica", value: "Łęknica"},
  {label: "Żary", value: "Żary"},
  {label: "Bełchatów", value: "Bełchatów"},
  {label: "Zelów", value: "Zelów"},
  {label: "Brzeziny", value: "Brzeziny"},
  {label: "Jeżów", value: "Jeżów"},
  {label: "Dąbrowice", value: "Dąbrowice"},
  {label: "Krośniewice", value: "Krośniewice"},
  {label: "Kutno", value: "Kutno"},
  {label: "Żychlin", value: "Żychlin"},
  {label: "Łask", value: "Łask"},
  {label: "Grabów", value: "Grabów"},
  {label: "Łęczyca", value: "Łęczyca"},
  {label: "Piątek", value: "Piątek"},
  {label: "Kiernozia", value: "Kiernozia"},
  {label: "Łowicz", value: "Łowicz"},
  {label: "Koluszki", value: "Koluszki"},
  {label: "Rzgów", value: "Rzgów"},
  {label: "Tuszyn", value: "Tuszyn"},
  {label: "Łódź", value: "Łódź"},
  {label: "Białaczów", value: "Białaczów"},
  {label: "Drzewica", value: "Drzewica"},
  {label: "Opoczno", value: "Opoczno"},
  {label: "Żarnów", value: "Żarnów"},
  {label: "Konstantynów Łódzki", value: "Konstantynów Łódzki"},
  {label: "Lutomiersk", value: "Lutomiersk"},
  {label: "Pabianice", value: "Pabianice"},
  {label: "Działoszyn", value: "Działoszyn"},
  {label: "Pajęczno", value: "Pajęczno"},
  {label: "Rozprza", value: "Rozprza"},
  {label: "Sulejów", value: "Sulejów"},
  {label: "Wolbórz", value: "Wolbórz"},
  {label: "Piotrków Trybunalski", value: "Piotrków Trybunalski"},
  {label: "Poddębice", value: "Poddębice"},
  {label: "Uniejów", value: "Uniejów"},
  {label: "Kamieńsk", value: "Kamieńsk"},
  {label: "Przedbórz", value: "Przedbórz"},
  {label: "Radomsko", value: "Radomsko"},
  {label: "Biała Rawska", value: "Biała Rawska"},
  {label: "Rawa Mazowiecka", value: "Rawa Mazowiecka"},
  {label: "Błaszki", value: "Błaszki"},
  {label: "Sieradz", value: "Sieradz"},
  {label: "Warta", value: "Warta"},
  {label: "Złoczew", value: "Złoczew"},
  {label: "Skierniewice", value: "Skierniewice"},
  {label: "Bolimów", value: "Bolimów"},
  {label: "Inowłódz", value: "Inowłódz"},
  {label: "Tomaszów Mazowiecki", value: "Tomaszów Mazowiecki"},
  {label: "Ujazd", value: "Ujazd"},
  {label: "Osjaków", value: "Osjaków"},
  {label: "Wieluń", value: "Wieluń"},
  {label: "Bolesławiec", value: "Bolesławiec"},
  {label: "Lututów", value: "Lututów"},
  {label: "Wieruszów", value: "Wieruszów"},
  {label: "Szadek", value: "Szadek"},
  {label: "Zduńska Wola", value: "Zduńska Wola"},
  {label: "Aleksandrów Łódzki", value: "Aleksandrów Łódzki"},
  {label: "Głowno", value: "Głowno"},
  {label: "Ozorków", value: "Ozorków"},
  {label: "Parzęczew", value: "Parzęczew"},
  {label: "Stryków", value: "Stryków"},
  {label: "Zgierz", value: "Zgierz"},
  {label: "Bochnia", value: "Bochnia"},
  {label: "Nowy Wiśnicz", value: "Nowy Wiśnicz"},
  {label: "Brzesko", value: "Brzesko"},
  {label: "Czchów", value: "Czchów"},
  {label: "Alwernia", value: "Alwernia"},
  {label: "Chrzanów", value: "Chrzanów"},
  {label: "Libiąż", value: "Libiąż"},
  {label: "Trzebinia", value: "Trzebinia"},
  {label: "Dąbrowa Tarnowska", value: "Dąbrowa Tarnowska"},
  {label: "Szczucin", value: "Szczucin"},
  {label: "Biecz", value: "Biecz"},
  {label: "Bobowa", value: "Bobowa"},
  {label: "Gorlice", value: "Gorlice"},
  {label: "Krzeszowice", value: "Krzeszowice"},
  {label: "Skała", value: "Skała"},
  {label: "Skawina", value: "Skawina"},
  {label: "Słomniki", value: "Słomniki"},
  {label: "Świątniki Górne", value: "Świątniki Górne"},
  {label: "Kraków", value: "Kraków"},
  {label: "Limanowa", value: "Limanowa"},
  {label: "Mszana Dolna", value: "Mszana Dolna"},
  {label: "Książ Wielki", value: "Książ Wielki"},
  {label: "Miechów", value: "Miechów"},
  {label: "Dobczyce", value: "Dobczyce"},
  {label: "Myślenice", value: "Myślenice"},
  {label: "Sułkowice", value: "Sułkowice"},
  {label: "Grybów", value: "Grybów"},
  {label: "Krynica-Zdrój", value: "Krynica-Zdrój"},
  {label: "Muszyna", value: "Muszyna"},
  {label: "Piwniczna-Zdrój", value: "Piwniczna-Zdrój"},
  {label: "Stary Sącz", value: "Stary Sącz"},
  {label: "Czarny Dunajec", value: "Czarny Dunajec"},
  {label: "Nowy Targ", value: "Nowy Targ"},
  {label: "Rabka-Zdrój", value: "Rabka-Zdrój"},
  {label: "Szczawnica", value: "Szczawnica"},
  {label: "Nowy Sącz", value: "Nowy Sącz"},
  {label: "Bukowno", value: "Bukowno"},
  {label: "Olkusz", value: "Olkusz"},
  {label: "Wolbrom", value: "Wolbrom"},
  {label: "Brzeszcze", value: "Brzeszcze"},
  {label: "Chełmek", value: "Chełmek"},
  {label: "Kęty", value: "Kęty"},
  {label: "Oświęcim", value: "Oświęcim"},
  {label: "Zator", value: "Zator"},
  {label: "Koszyce", value: "Koszyce"},
  {label: "Nowe Brzesko", value: "Nowe Brzesko"},
  {label: "Proszowice", value: "Proszowice"},
  {label: "Jordanów", value: "Jordanów"},
  {label: "Maków Podhalański", value: "Maków Podhalański"},
  {label: "Sucha Beskidzka", value: "Sucha Beskidzka"},
  {label: "Ciężkowice", value: "Ciężkowice"},
  {label: "Radłów", value: "Radłów"},
  {label: "Ryglice", value: "Ryglice"},
  {label: "Tuchów", value: "Tuchów"},
  {label: "Wojnicz", value: "Wojnicz"},
  {label: "Zakliczyn", value: "Zakliczyn"},
  {label: "Żabno", value: "Żabno"},
  {label: "Tarnów", value: "Tarnów"},
  {label: "Zakopane", value: "Zakopane"},
  {label: "Andrychów", value: "Andrychów"},
  {label: "Kalwaria Zebrzydowska", value: "Kalwaria Zebrzydowska"},
  {label: "Wadowice", value: "Wadowice"},
  {label: "Niepołomice", value: "Niepołomice"},
  {label: "Wieliczka", value: "Wieliczka"},
  {label: "Białobrzegi", value: "Białobrzegi"},
  {label: "Wyśmierzyce", value: "Wyśmierzyce"},
  {label: "Ciechanów", value: "Ciechanów"},
  {label: "Glinojeck", value: "Glinojeck"},
  {label: "Garwolin", value: "Garwolin"},
  {label: "Łaskarzew", value: "Łaskarzew"},
  {label: "Maciejowice", value: "Maciejowice"},
  {label: "Pilawa", value: "Pilawa"},
  {label: "Żelechów", value: "Żelechów"},
  {label: "Gostynin", value: "Gostynin"},
  {label: "Sanniki", value: "Sanniki"},
  {label: "Grodzisk Mazowiecki", value: "Grodzisk Mazowiecki"},
  {label: "Milanówek", value: "Milanówek"},
  {label: "Podkowa Leśna", value: "Podkowa Leśna"},
  {label: "Grójec", value: "Grójec"},
  {label: "Mogielnica", value: "Mogielnica"},
  {label: "Nowe Miasto nad Pilicą", value: "Nowe Miasto nad Pilicą"},
  {label: "Warka", value: "Warka"},
  {label: "Głowaczów", value: "Głowaczów"},
  {label: "Kozienice", value: "Kozienice"},
  {label: "Magnuszew", value: "Magnuszew"},
  {label: "Legionowo", value: "Legionowo"},
  {label: "Serock", value: "Serock"},
  {label: "Ciepielów", value: "Ciepielów"},
  {label: "Lipsko", value: "Lipsko"},
  {label: "Sienno", value: "Sienno"},
  {label: "Solec nad Wisłą", value: "Solec nad Wisłą"},
  {label: "Łosice", value: "Łosice"},
  {label: "Maków Mazowiecki", value: "Maków Mazowiecki"},
  {label: "Różan", value: "Różan"},
  {label: "Cegłów", value: "Cegłów"},
  {label: "Dobre", value: "Dobre"},
  {label: "Halinów", value: "Halinów"},
  {label: "Kałuszyn", value: "Kałuszyn"},
  {label: "Latowicz", value: "Latowicz"},
  {label: "Mińsk Mazowiecki", value: "Mińsk Mazowiecki"},
  {label: "Mrozy", value: "Mrozy"},
  {label: "Siennica", value: "Siennica"},
  {label: "Sulejówek", value: "Sulejówek"},
  {label: "Mława", value: "Mława"},
  {label: "Nasielsk", value: "Nasielsk"},
  {label: "Nowy Dwór Mazowiecki", value: "Nowy Dwór Mazowiecki"},
  {label: "Zakroczym", value: "Zakroczym"},
  {label: "Myszyniec", value: "Myszyniec"},
  {label: "Ostrołęka", value: "Ostrołęka"},
  {label: "Brok", value: "Brok"},
  {label: "Ostrów Mazowiecka", value: "Ostrów Mazowiecka"},
  {label: "Józefów", value: "Józefów"},
  {label: "Karczew", value: "Karczew"},
  {label: "Osieck", value: "Osieck"},
  {label: "Otwock", value: "Otwock"},
  {label: "Góra Kalwaria", value: "Góra Kalwaria"},
  {label: "Konstancin-Jeziorna", value: "Konstancin-Jeziorna"},
  {label: "Piaseczno", value: "Piaseczno"},
  {label: "Tarczyn", value: "Tarczyn"},
  {label: "Płock", value: "Płock"},
  {label: "Bodzanów", value: "Bodzanów"},
  {label: "Drobin", value: "Drobin"},
  {label: "Gąbin", value: "Gąbin"},
  {label: "Wyszogród", value: "Wyszogród"},
  {label: "Czerwińsk nad Wisłą", value: "Czerwińsk nad Wisłą"},
  {label: "Nowe Miasto", value: "Nowe Miasto"},
  {label: "Płońsk", value: "Płońsk"},
  {label: "Raciąż", value: "Raciąż"},
  {label: "Sochocin", value: "Sochocin"},
  {label: "Brwinów", value: "Brwinów"},
  {label: "Piastów", value: "Piastów"},
  {label: "Pruszków", value: "Pruszków"},
  {label: "Chorzele", value: "Chorzele"},
  {label: "Przasnysz", value: "Przasnysz"},
  {label: "Gielniów", value: "Gielniów"},
  {label: "Odrzywół", value: "Odrzywół"},
  {label: "Przysucha", value: "Przysucha"},
  {label: "Pułtusk", value: "Pułtusk"},
  {label: "Radom", value: "Radom"},
  {label: "Iłża", value: "Iłża"},
  {label: "Jedlnia-Letnisko", value: "Jedlnia-Letnisko"},
  {label: "Pionki", value: "Pionki"},
  {label: "Przytyk", value: "Przytyk"},
  {label: "Skaryszew", value: "Skaryszew"},
  {label: "Siedlce", value: "Siedlce"},
  {label: "Mordy", value: "Mordy"},
  {label: "Sierpc", value: "Sierpc"},
  {label: "Sochaczew", value: "Sochaczew"},
  {label: "Kosów Lacki", value: "Kosów Lacki"},
  {label: "Sokołów Podlaski", value: "Sokołów Podlaski"},
  {label: "Jastrząb", value: "Jastrząb"},
  {label: "Szydłowiec", value: "Szydłowiec"},
  {label: "Warszawa", value: "Warszawa"},
  {label: "Błonie", value: "Błonie"},
  {label: "Łomianki", value: "Łomianki"},
  {label: "Ożarów Mazowiecki", value: "Ożarów Mazowiecki"},
  {label: "Łochów", value: "Łochów"},
  {label: "Węgrów", value: "Węgrów"},
  {label: "Jadów", value: "Jadów"},
  {label: "Kobyłka", value: "Kobyłka"},
  {label: "Marki", value: "Marki"},
  {label: "Radzymin", value: "Radzymin"},
  {label: "Tłuszcz", value: "Tłuszcz"},
  {label: "Wołomin", value: "Wołomin"},
  {label: "Ząbki", value: "Ząbki"},
  {label: "Zielonka", value: "Zielonka"},
  {label: "Wyszków", value: "Wyszków"},
  {label: "Zwoleń", value: "Zwoleń"},
  {label: "Bieżuń", value: "Bieżuń"},
  {label: "Lubowidz", value: "Lubowidz"},
  {label: "Żuromin", value: "Żuromin"},
  {label: "Mszczonów", value: "Mszczonów"},
  {label: "Wiskitki", value: "Wiskitki"},
  {label: "Żyrardów", value: "Żyrardów"},
  {label: "Brzeg", value: "Brzeg"},
  {label: "Grodków", value: "Grodków"},
  {label: "Lewin Brzeski", value: "Lewin Brzeski"},
  {label: "Baborów", value: "Baborów"},
  {label: "Głubczyce", value: "Głubczyce"},
  {label: "Kietrz", value: "Kietrz"},
  {label: "Kędzierzyn-Koźle", value: "Kędzierzyn-Koźle"},
  {label: "Byczyna", value: "Byczyna"},
  {label: "Kluczbork", value: "Kluczbork"},
  {label: "Wołczyn", value: "Wołczyn"},
  {label: "Gogolin", value: "Gogolin"},
  {label: "Krapkowice", value: "Krapkowice"},
  {label: "Strzeleczki", value: "Strzeleczki"},
  {label: "Zdzieszowice", value: "Zdzieszowice"},
  {label: "Namysłów", value: "Namysłów"},
  {label: "Głuchołazy", value: "Głuchołazy"},
  {label: "Korfantów", value: "Korfantów"},
  {label: "Nysa", value: "Nysa"},
  {label: "Otmuchów", value: "Otmuchów"},
  {label: "Paczków", value: "Paczków"},
  {label: "Dobrodzień", value: "Dobrodzień"},
  {label: "Gorzów Śląski", value: "Gorzów Śląski"},
  {label: "Olesno", value: "Olesno"},
  {label: "Praszka", value: "Praszka"},
  {label: "Opole", value: "Opole"},
  {label: "Niemodlin", value: "Niemodlin"},
  {label: "Ozimek", value: "Ozimek"},
  {label: "Prószków", value: "Prószków"},
  {label: "Tułowice", value: "Tułowice"},
  {label: "Biała", value: "Biała"},
  {label: "Głogówek", value: "Głogówek"},
  {label: "Prudnik", value: "Prudnik"},
  {label: "Kolonowskie", value: "Kolonowskie"},
  {label: "Leśnica", value: "Leśnica"},
  {label: "Strzelce Opolskie", value: "Strzelce Opolskie"},
  {label: "Ujazd", value: "Ujazd"},
  {label: "Zawadzkie", value: "Zawadzkie"},
  {label: "Ustrzyki Dolne", value: "Ustrzyki Dolne"},
  {label: "Brzozów", value: "Brzozów"},
  {label: "Brzostek", value: "Brzostek"},
  {label: "Dębica", value: "Dębica"},
  {label: "Pilzno", value: "Pilzno"},
  {label: "Jarosław", value: "Jarosław"},
  {label: "Pruchnik", value: "Pruchnik"},
  {label: "Radymno", value: "Radymno"},
  {label: "Jasło", value: "Jasło"},
  {label: "Kołaczyce", value: "Kołaczyce"},
  {label: "Kolbuszowa", value: "Kolbuszowa"},
  {label: "Krosno", value: "Krosno"},
  {label: "Dukla", value: "Dukla"},
  {label: "Iwonicz-Zdrój", value: "Iwonicz-Zdrój"},
  {label: "Jedlicze", value: "Jedlicze"},
  {label: "Rymanów", value: "Rymanów"},
  {label: "Lesko", value: "Lesko"},
  {label: "Leżajsk", value: "Leżajsk"},
  {label: "Nowa Sarzyna", value: "Nowa Sarzyna"},
  {label: "Cieszanów", value: "Cieszanów"},
  {label: "Lubaczów", value: "Lubaczów"},
  {label: "Narol", value: "Narol"},
  {label: "Oleszyce", value: "Oleszyce"},
  {label: "Łańcut", value: "Łańcut"},
  {label: "Mielec", value: "Mielec"},
  {label: "Przecław", value: "Przecław"},
  {label: "Radomyśl Wielki", value: "Radomyśl Wielki"},
  {label: "Nisko", value: "Nisko"},
  {label: "Rudnik nad Sanem", value: "Rudnik nad Sanem"},
  {label: "Ulanów", value: "Ulanów"},
  {label: "Bircza", value: "Bircza"},
  {label: "Dubiecko", value: "Dubiecko"},
  {label: "Przemyśl", value: "Przemyśl"},
  {label: "Jawornik Polski", value: "Jawornik Polski"},
  {label: "Kańczuga", value: "Kańczuga"},
  {label: "Przeworsk", value: "Przeworsk"},
  {label: "Sieniawa", value: "Sieniawa"},
  {label: "Ropczyce", value: "Ropczyce"},
  {label: "Sędziszów Małopolski", value: "Sędziszów Małopolski"},
  {label: "Błażowa", value: "Błażowa"},
  {label: "Boguchwała", value: "Boguchwała"},
  {label: "Dynów", value: "Dynów"},
  {label: "Głogów Małopolski", value: "Głogów Małopolski"},
  {label: "Sokołów Małopolski", value: "Sokołów Małopolski"},
  {label: "Tyczyn", value: "Tyczyn"},
  {label: "Rzeszów", value: "Rzeszów"},
  {label: "Sanok", value: "Sanok"},
  {label: "Zagórz", value: "Zagórz"},
  {label: "Stalowa Wola", value: "Stalowa Wola"},
  {label: "Zaklików", value: "Zaklików"},
  {label: "Strzyżów", value: "Strzyżów"},
  {label: "Tarnobrzeg", value: "Tarnobrzeg"},
  {label: "Baranów Sandomierski", value: "Baranów Sandomierski"},
  {label: "Nowa Dęba", value: "Nowa Dęba"},
  {label: "Augustów", value: "Augustów"},
  {label: "Lipsk", value: "Lipsk"},
  {label: "Choroszcz", value: "Choroszcz"},
  {label: "Czarna Białostocka", value: "Czarna Białostocka"},
  {label: "Łapy", value: "Łapy"},
  {label: "Michałowo", value: "Michałowo"},
  {label: "Supraśl", value: "Supraśl"},
  {label: "Suraż", value: "Suraż"},
  {label: "Tykocin", value: "Tykocin"},
  {label: "Wasilków", value: "Wasilków"},
  {label: "Zabłudów", value: "Zabłudów"},
  {label: "Białystok", value: "Białystok"},
  {label: "Bielsk Podlaski", value: "Bielsk Podlaski"},
  {label: "Brańsk", value: "Brańsk"},
  {label: "Grajewo", value: "Grajewo"},
  {label: "Rajgród", value: "Rajgród"},
  {label: "Szczuczyn", value: "Szczuczyn"},
  {label: "Hajnówka", value: "Hajnówka"},
  {label: "Kleszczele", value: "Kleszczele"},
  {label: "Kolno", value: "Kolno"},
  {label: "Stawiski", value: "Stawiski"},
  {label: "Łomża", value: "Łomża"},
  {label: "Jedwabne", value: "Jedwabne"},
  {label: "Nowogród", value: "Nowogród"},
  {label: "Goniądz", value: "Goniądz"},
  {label: "Knyszyn", value: "Knyszyn"},
  {label: "Mońki", value: "Mońki"},
  {label: "Sejny", value: "Sejny"},
  {label: "Drohiczyn", value: "Drohiczyn"},
  {label: "Siemiatycze", value: "Siemiatycze"},
  {label: "Dąbrowa Białostocka", value: "Dąbrowa Białostocka"},
  {label: "Krynki", value: "Krynki"},
  {label: "Sokółka", value: "Sokółka"},
  {label: "Suchowola", value: "Suchowola"},
  {label: "Suwałki", value: "Suwałki"},
  {label: "Ciechanowiec", value: "Ciechanowiec"},
  {label: "Czyżew", value: "Czyżew"},
  {label: "Szepietowo", value: "Szepietowo"},
  {label: "Wysokie Mazowieckie", value: "Wysokie Mazowieckie"},
  {label: "Zambrów", value: "Zambrów"},
  {label: "Bytów", value: "Bytów"},
  {label: "Miastko", value: "Miastko"},
  {label: "Brusy", value: "Brusy"},
  {label: "Chojnice", value: "Chojnice"},
  {label: "Czersk", value: "Czersk"},
  {label: "Czarne", value: "Czarne"},
  {label: "Człuchów", value: "Człuchów"},
  {label: "Debrzno", value: "Debrzno"},
  {label: "Gdańsk", value: "Gdańsk"},
  {label: "Pruszcz Gdański", value: "Pruszcz Gdański"},
  {label: "Gdynia", value: "Gdynia"},
  {label: "Kartuzy", value: "Kartuzy"},
  {label: "Żukowo", value: "Żukowo"},
  {label: "Kościerzyna", value: "Kościerzyna"},
  {label: "Kwidzyn", value: "Kwidzyn"},
  {label: "Prabuty", value: "Prabuty"},
  {label: "Lębork", value: "Lębork"},
  {label: "Łeba", value: "Łeba"},
  {label: "Malbork", value: "Malbork"},
  {label: "Nowy Staw", value: "Nowy Staw"},
  {label: "Krynica Morska", value: "Krynica Morska"},
  {label: "Nowy Dwór Gdański", value: "Nowy Dwór Gdański"},
  {label: "Hel", value: "Hel"},
  {label: "Jastarnia", value: "Jastarnia"},
  {label: "Puck", value: "Puck"},
  {label: "Władysławowo", value: "Władysławowo"},
  {label: "Słupsk", value: "Słupsk"},
  {label: "Kępice", value: "Kępice"},
  {label: "Ustka", value: "Ustka"},
  {label: "Sopot", value: "Sopot"},
  {label: "Czarna Woda", value: "Czarna Woda"},
  {label: "Skarszewy", value: "Skarszewy"},
  {label: "Skórcz", value: "Skórcz"},
  {label: "Starogard Gdański", value: "Starogard Gdański"},
  {label: "Dzierzgoń", value: "Dzierzgoń"},
  {label: "Sztum", value: "Sztum"},
  {label: "Gniew", value: "Gniew"},
  {label: "Pelplin", value: "Pelplin"},
  {label: "Tczew", value: "Tczew"},
  {label: "Reda", value: "Reda"},
  {label: "Rumia", value: "Rumia"},
  {label: "Wejherowo", value: "Wejherowo"},
  {label: "Będzin", value: "Będzin"},
  {label: "Czeladź", value: "Czeladź"},
  {label: "Siewierz", value: "Siewierz"},
  {label: "Sławków", value: "Sławków"},
  {label: "Wojkowice", value: "Wojkowice"},
  {label: "Czechowice-Dziedzice", value: "Czechowice-Dziedzice"},
  {label: "Szczyrk", value: "Szczyrk"},
  {label: "Wilamowice", value: "Wilamowice"},
  {label: "Bielsko-Biała", value: "Bielsko-Biała"},
  {label: "Bieruń", value: "Bieruń"},
  {label: "Imielin", value: "Imielin"},
  {label: "Lędziny", value: "Lędziny"},
  {label: "Bytom", value: "Bytom"},
  {label: "Chorzów", value: "Chorzów"},
  {label: "Cieszyn", value: "Cieszyn"},
  {label: "Skoczów", value: "Skoczów"},
  {label: "Strumień", value: "Strumień"},
  {label: "Ustroń", value: "Ustroń"},
  {label: "Wisła", value: "Wisła"},
  {label: "Częstochowa", value: "Częstochowa"},
  {label: "Blachownia", value: "Blachownia"},
  {label: "Koniecpol", value: "Koniecpol"},
  {label: "Olsztyn", value: "Olsztyn"},
  {label: "Przyrów", value: "Przyrów"},
  {label: "Dąbrowa Górnicza", value: "Dąbrowa Górnicza"},
  {label: "Gliwice", value: "Gliwice"},
  {label: "Knurów", value: "Knurów"},
  {label: "Pyskowice", value: "Pyskowice"},
  {label: "Sośnicowice", value: "Sośnicowice"},
  {label: "Toszek", value: "Toszek"},
  {label: "Jastrzębie-Zdrój", value: "Jastrzębie-Zdrój"},
  {label: "Jaworzno", value: "Jaworzno"},
  {label: "Katowice", value: "Katowice"},
  {label: "Kłobuck", value: "Kłobuck"},
  {label: "Krzepice", value: "Krzepice"},
  {label: "Lubliniec", value: "Lubliniec"},
  {label: "Woźniki", value: "Woźniki"},
  {label: "Łaziska Górne", value: "Łaziska Górne"},
  {label: "Mikołów", value: "Mikołów"},
  {label: "Orzesze", value: "Orzesze"},
  {label: "Mysłowice", value: "Mysłowice"},
  {label: "Koziegłowy", value: "Koziegłowy"},
  {label: "Myszków", value: "Myszków"},
  {label: "Żarki", value: "Żarki"},
  {label: "Piekary Śląskie", value: "Piekary Śląskie"},
  {label: "Pszczyna", value: "Pszczyna"},
  {label: "Krzanowice", value: "Krzanowice"},
  {label: "Kuźnia Raciborska", value: "Kuźnia Raciborska"},
  {label: "Racibórz", value: "Racibórz"},
  {label: "Ruda Śląska", value: "Ruda Śląska"},
  {label: "Czerwionka-Leszczyny", value: "Czerwionka-Leszczyny"},
  {label: "Rybnik", value: "Rybnik"},
  {label: "Siemianowice Śląskie", value: "Siemianowice Śląskie"},
  {label: "Sosnowiec", value: "Sosnowiec"},
  {label: "Świętochłowice", value: "Świętochłowice"},
  {label: "Kalety", value: "Kalety"},
  {label: "Miasteczko Śląskie", value: "Miasteczko Śląskie"},
  {label: "Radzionków", value: "Radzionków"},
  {label: "Tarnowskie Góry", value: "Tarnowskie Góry"},
  {label: "Tychy", value: "Tychy"},
  {label: "Pszów", value: "Pszów"},
  {label: "Radlin", value: "Radlin"},
  {label: "Rydułtowy", value: "Rydułtowy"},
  {label: "Wodzisław Śląski", value: "Wodzisław Śląski"},
  {label: "Zabrze", value: "Zabrze"},
  {label: "Łazy", value: "Łazy"},
  {label: "Ogrodzieniec", value: "Ogrodzieniec"},
  {label: "Pilica", value: "Pilica"},
  {label: "Poręba", value: "Poręba"},
  {label: "Szczekociny", value: "Szczekociny"},
  {label: "Włodowice", value: "Włodowice"},
  {label: "Zawiercie", value: "Zawiercie"},
  {label: "Żory", value: "Żory"},
  {label: "Żywiec", value: "Żywiec"},
  {label: "Busko-Zdrój", value: "Busko-Zdrój"},
  {label: "Nowy Korczyn", value: "Nowy Korczyn"},
  {label: "Pacanów", value: "Pacanów"},
  {label: "Stopnica", value: "Stopnica"},
  {label: "Wiślica", value: "Wiślica"},
  {label: "Jędrzejów", value: "Jędrzejów"},
  {label: "Małogoszcz", value: "Małogoszcz"},
  {label: "Sędziszów", value: "Sędziszów"},
  {label: "Wodzisław", value: "Wodzisław"},
  {label: "Kazimierza Wielka", value: "Kazimierza Wielka"},
  {label: "Opatowiec", value: "Opatowiec"},
  {label: "Skalbmierz", value: "Skalbmierz"},
  {label: "Kielce", value: "Kielce"},
  {label: "Bodzentyn", value: "Bodzentyn"},
  {label: "Chęciny", value: "Chęciny"},
  {label: "Chmielnik", value: "Chmielnik"},
  {label: "Daleszyce", value: "Daleszyce"},
  {label: "Łagów", value: "Łagów"},
  {label: "Łopuszno", value: "Łopuszno"},
  {label: "Morawica", value: "Morawica"},
  {label: "Nowa Słupia", value: "Nowa Słupia"},
  {label: "Piekoszów", value: "Piekoszów"},
  {label: "Pierzchnica", value: "Pierzchnica"},
  {label: "Gowarczów", value: "Gowarczów"},
  {label: "Końskie", value: "Końskie"},
  {label: "Radoszyce", value: "Radoszyce"},
  {label: "Stąporków", value: "Stąporków"},
  {label: "Iwaniska", value: "Iwaniska"},
  {label: "Opatów", value: "Opatów"},
  {label: "Ożarów", value: "Ożarów"},
  {label: "Ćmielów", value: "Ćmielów"},
  {label: "Kunów", value: "Kunów"},
  {label: "Ostrowiec Świętokrzyski", value: "Ostrowiec Świętokrzyski"},
  {label: "Działoszyce", value: "Działoszyce"},
  {label: "Pińczów", value: "Pińczów"},
  {label: "Klimontów", value: "Klimontów"},
  {label: "Koprzywnica", value: "Koprzywnica"},
  {label: "Sandomierz", value: "Sandomierz"},
  {label: "Zawichost", value: "Zawichost"},
  {label: "Skarżysko-Kamienna", value: "Skarżysko-Kamienna"},
  {label: "Suchedniów", value: "Suchedniów"},
  {label: "Starachowice", value: "Starachowice"},
  {label: "Wąchock", value: "Wąchock"},
  {label: "Bogoria", value: "Bogoria"},
  {label: "Oleśnica", value: "Oleśnica"},
  {label: "Osiek", value: "Osiek"},
  {label: "Połaniec", value: "Połaniec"},
  {label: "Staszów", value: "Staszów"},
  {label: "Szydłów", value: "Szydłów"},
  {label: "Włoszczowa", value: "Włoszczowa"},
  {label: "Bartoszyce", value: "Bartoszyce"},
  {label: "Bisztynek", value: "Bisztynek"},
  {label: "Górowo Iławeckie", value: "Górowo Iławeckie"},
  {label: "Sępopol", value: "Sępopol"},
  {label: "Braniewo", value: "Braniewo"},
  {label: "Frombork", value: "Frombork"},
  {label: "Pieniężno", value: "Pieniężno"},
  {label: "Działdowo", value: "Działdowo"},
  {label: "Lidzbark", value: "Lidzbark"},
  {label: "Elbląg", value: "Elbląg"},
  {label: "Młynary", value: "Młynary"},
  {label: "Pasłęk", value: "Pasłęk"},
  {label: "Tolkmicko", value: "Tolkmicko"},
  {label: "Ełk", value: "Ełk"},
  {label: "Giżycko", value: "Giżycko"},
  {label: "Ryn", value: "Ryn"},
  {label: "Gołdap", value: "Gołdap"},
  {label: "Iława", value: "Iława"},
  {label: "Kisielice", value: "Kisielice"},
  {label: "Lubawa", value: "Lubawa"},
  {label: "Susz", value: "Susz"},
  {label: "Zalewo", value: "Zalewo"},
  {label: "Kętrzyn", value: "Kętrzyn"},
  {label: "Korsze", value: "Korsze"},
  {label: "Reszel", value: "Reszel"},
  {label: "Lidzbark Warmiński", value: "Lidzbark Warmiński"},
  {label: "Orneta", value: "Orneta"},
  {label: "Mikołajki", value: "Mikołajki"},
  {label: "Mrągowo", value: "Mrągowo"},
  {label: "Nidzica", value: "Nidzica"},
  {label: "Nowe Miasto Lubawskie", value: "Nowe Miasto Lubawskie"},
  {label: "Olecko", value: "Olecko"},
  {label: "Olsztyn", value: "Olsztyn"},
  {label: "Barczewo", value: "Barczewo"},
  {label: "Biskupiec", value: "Biskupiec"},
  {label: "Dobre Miasto", value: "Dobre Miasto"},
  {label: "Jeziorany", value: "Jeziorany"},
  {label: "Olsztynek", value: "Olsztynek"},
  {label: "Miłakowo", value: "Miłakowo"},
  {label: "Miłomłyn", value: "Miłomłyn"},
  {label: "Morąg", value: "Morąg"},
  {label: "Ostróda", value: "Ostróda"},
  {label: "Biała Piska", value: "Biała Piska"},
  {label: "Orzysz", value: "Orzysz"},
  {label: "Pisz", value: "Pisz"},
  {label: "Ruciane-Nida", value: "Ruciane-Nida"},
  {label: "Pasym", value: "Pasym"},
  {label: "Szczytno", value: "Szczytno"},
  {label: "Wielbark", value: "Wielbark"},
  {label: "Węgorzewo", value: "Węgorzewo"},
  {label: "Budzyń", value: "Budzyń"},
  {label: "Chodzież", value: "Chodzież"},
  {label: "Margonin", value: "Margonin"},
  {label: "Szamocin", value: "Szamocin"},
  {label: "Czarnków", value: "Czarnków"},
  {label: "Krzyż Wielkopolski", value: "Krzyż Wielkopolski"},
  {label: "Trzcianka", value: "Trzcianka"},
  {label: "Wieleń", value: "Wieleń"},
  {label: "Czerniejewo", value: "Czerniejewo"},
  {label: "Gniezno", value: "Gniezno"},
  {label: "Kłecko", value: "Kłecko"},
  {label: "Trzemeszno", value: "Trzemeszno"},
  {label: "Witkowo", value: "Witkowo"},
  {label: "Borek Wielkopolski", value: "Borek Wielkopolski"},
  {label: "Gostyń", value: "Gostyń"},
  {label: "Krobia", value: "Krobia"},
  {label: "Pogorzela", value: "Pogorzela"},
  {label: "Poniec", value: "Poniec"},
  {label: "Grodzisk Wielkopolski", value: "Grodzisk Wielkopolski"},
  {label: "Rakoniewice", value: "Rakoniewice"},
  {label: "Wielichowo", value: "Wielichowo"},
  {label: "Jaraczewo", value: "Jaraczewo"},
  {label: "Jarocin", value: "Jarocin"},
  {label: "Żerków", value: "Żerków"},
  {label: "Koźminek", value: "Koźminek"},
  {label: "Opatówek", value: "Opatówek"},
  {label: "Stawiszyn", value: "Stawiszyn"},
  {label: "Kalisz", value: "Kalisz"},
  {label: "Kępno", value: "Kępno"},
  {label: "Rychtal", value: "Rychtal"},
  {label: "Dąbie", value: "Dąbie"},
  {label: "Kłodawa", value: "Kłodawa"},
  {label: "Koło", value: "Koło"},
  {label: "Przedecz", value: "Przedecz"},
  {label: "Konin", value: "Konin"},
  {label: "Golina", value: "Golina"},
  {label: "Kleczew", value: "Kleczew"},
  {label: "Rychwał", value: "Rychwał"},
  {label: "Sompolno", value: "Sompolno"},
  {label: "Ślesin", value: "Ślesin"},
  {label: "Czempiń", value: "Czempiń"},
  {label: "Kościan", value: "Kościan"},
  {label: "Krzywiń", value: "Krzywiń"},
  {label: "Śmigiel", value: "Śmigiel"},
  {label: "Kobylin", value: "Kobylin"},
  {label: "Koźmin Wielkopolski", value: "Koźmin Wielkopolski"},
  {label: "Krotoszyn", value: "Krotoszyn"},
  {label: "Sulmierzyce", value: "Sulmierzyce"},
  {label: "Zduny", value: "Zduny"},
  {label: "Osieczna", value: "Osieczna"},
  {label: "Rydzyna", value: "Rydzyna"},
  {label: "Leszno", value: "Leszno"},
  {label: "Międzychód", value: "Międzychód"},
  {label: "Sieraków", value: "Sieraków"},
  {label: "Lwówek", value: "Lwówek"},
  {label: "Nowy Tomyśl", value: "Nowy Tomyśl"},
  {label: "Opalenica", value: "Opalenica"},
  {label: "Zbąszyń", value: "Zbąszyń"},
  {label: "Oborniki", value: "Oborniki"},
  {label: "Rogoźno", value: "Rogoźno"},
  {label: "Nowe Skalmierzyce", value: "Nowe Skalmierzyce"},
  {label: "Odolanów", value: "Odolanów"},
  {label: "Ostrów Wielkopolski", value: "Ostrów Wielkopolski"},
  {label: "Raszków", value: "Raszków"},
  {label: "Grabów nad Prosną", value: "Grabów nad Prosną"},
  {label: "Mikstat", value: "Mikstat"},
  {label: "Ostrzeszów", value: "Ostrzeszów"},
  {label: "Kaczory", value: "Kaczory"},
  {label: "Łobżenica", value: "Łobżenica"},
  {label: "Miasteczko Krajeńskie", value: "Miasteczko Krajeńskie"},
  {label: "Piła", value: "Piła"},
  {label: "Ujście", value: "Ujście"},
  {label: "Wyrzysk", value: "Wyrzysk"},
  {label: "Wysoka", value: "Wysoka"},
  {label: "Chocz", value: "Chocz"},
  {label: "Dobrzyca", value: "Dobrzyca"},
  {label: "Pleszew", value: "Pleszew"},
  {label: "Poznań", value: "Poznań"},
  {label: "Buk", value: "Buk"},
  {label: "Kostrzyn", value: "Kostrzyn"},
  {label: "Kórnik", value: "Kórnik"},
  {label: "Luboń", value: "Luboń"},
  {label: "Mosina", value: "Mosina"},
  {label: "Murowana Goślina", value: "Murowana Goślina"},
  {label: "Pobiedziska", value: "Pobiedziska"},
  {label: "Puszczykowo", value: "Puszczykowo"},
  {label: "Stęszew", value: "Stęszew"},
  {label: "Swarzędz", value: "Swarzędz"},
  {label: "Bojanowo", value: "Bojanowo"},
  {label: "Jutrosin", value: "Jutrosin"},
  {label: "Miejska Górka", value: "Miejska Górka"},
  {label: "Rawicz", value: "Rawicz"},
  {label: "Słupca", value: "Słupca"},
  {label: "Zagórów", value: "Zagórów"},
  {label: "Obrzycko", value: "Obrzycko"},
  {label: "Ostroróg", value: "Ostroróg"},
  {label: "Pniewy", value: "Pniewy"},
  {label: "Szamotuły", value: "Szamotuły"},
  {label: "Wronki", value: "Wronki"},
  {label: "Środa Wielkopolska", value: "Środa Wielkopolska"},
  {label: "Dolsk", value: "Dolsk"},
  {label: "Książ Wielkopolski", value: "Książ Wielkopolski"},
  {label: "Śrem", value: "Śrem"},
  {label: "Dobra", value: "Dobra"},
  {label: "Tuliszków", value: "Tuliszków"},
  {label: "Turek", value: "Turek"},
  {label: "Gołańcz", value: "Gołańcz"},
  {label: "Mieścisko", value: "Mieścisko"},
  {label: "Skoki", value: "Skoki"},
  {label: "Wągrowiec", value: "Wągrowiec"},
  {label: "Wolsztyn", value: "Wolsztyn"},
  {label: "Miłosław", value: "Miłosław"},
  {label: "Nekla", value: "Nekla"},
  {label: "Pyzdry", value: "Pyzdry"},
  {label: "Września", value: "Września"},
  {label: "Jastrowie", value: "Jastrowie"},
  {label: "Krajenka", value: "Krajenka"},
  {label: "Okonek", value: "Okonek"},
  {label: "Złotów", value: "Złotów"},
  {label: "Białogard", value: "Białogard"},
  {label: "Karlino", value: "Karlino"},
  {label: "Tychowo", value: "Tychowo"},
  {label: "Choszczno", value: "Choszczno"},
  {label: "Drawno", value: "Drawno"},
  {label: "Pełczyce", value: "Pełczyce"},
  {label: "Recz", value: "Recz"},
  {label: "Czaplinek", value: "Czaplinek"},
  {label: "Drawsko Pomorskie", value: "Drawsko Pomorskie"},
  {label: "Kalisz Pomorski", value: "Kalisz Pomorski"},
  {label: "Złocieniec", value: "Złocieniec"},
  {label: "Goleniów", value: "Goleniów"},
  {label: "Maszewo", value: "Maszewo"},
  {label: "Nowogard", value: "Nowogard"},
  {label: "Stepnica", value: "Stepnica"},
  {label: "Gryfice", value: "Gryfice"},
  {label: "Płoty", value: "Płoty"},
  {label: "Trzebiatów", value: "Trzebiatów"},
  {label: "Cedynia", value: "Cedynia"},
  {label: "Chojna", value: "Chojna"},
  {label: "Gryfino", value: "Gryfino"},
  {label: "Mieszkowice", value: "Mieszkowice"},
  {label: "Moryń", value: "Moryń"},
  {label: "Trzcińsko-Zdrój", value: "Trzcińsko-Zdrój"},
  {label: "Dziwnów", value: "Dziwnów"},
  {label: "Golczewo", value: "Golczewo"},
  {label: "Kamień Pomorski", value: "Kamień Pomorski"},
  {label: "Międzyzdroje", value: "Międzyzdroje"},
  {label: "Wolin", value: "Wolin"},
  {label: "Gościno", value: "Gościno"},
  {label: "Kołobrzeg", value: "Kołobrzeg"},
  {label: "Koszalin", value: "Koszalin"},
  {label: "Bobolice", value: "Bobolice"},
  {label: "Mielno", value: "Mielno"},
  {label: "Polanów", value: "Polanów"},
  {label: "Sianów", value: "Sianów"},
  {label: "Dobra", value: "Dobra"},
  {label: "Łobez", value: "Łobez"},
  {label: "Resko", value: "Resko"},
  {label: "Węgorzyno", value: "Węgorzyno"},
  {label: "Barlinek", value: "Barlinek"},
  {label: "Dębno", value: "Dębno"},
  {label: "Myślibórz", value: "Myślibórz"},
  {label: "Nowe Warpno", value: "Nowe Warpno"},
  {label: "Police", value: "Police"},
  {label: "Lipiany", value: "Lipiany"},
  {label: "Pyrzyce", value: "Pyrzyce"},
  {label: "Darłowo", value: "Darłowo"},
  {label: "Sławno", value: "Sławno"},
  {label: "Chociwel", value: "Chociwel"},
  {label: "Dobrzany", value: "Dobrzany"},
  {label: "Ińsko", value: "Ińsko"},
  {label: "Stargard", value: "Stargard"},
  {label: "Suchań", value: "Suchań"},
  {label: "Szczecin", value: "Szczecin"},
  {label: "Barwice", value: "Barwice"},
  {label: "Biały Bór", value: "Biały Bór"},
  {label: "Borne Sulinowo", value: "Borne Sulinowo"},
  {label: "Szczecinek", value: "Szczecinek"},
  {label: "Połczyn-Zdrój", value: "Połczyn-Zdrój"},
  {label: "Świdwin", value: "Świdwin"},
  {label: "Świnoujście", value: "Świnoujście"},
  {label: "Człopa", value: "Człopa"},
  {label: "Mirosławiec", value: "Mirosławiec"},
  {label: "Tuczno", value: "Tuczno"},
  {label: "Wałcz", value: "Wałcz"}
  ]