export type Trainer = {
  about: string | null;
  city: string | null;
  created_at: string;
  diet_plan: boolean | null;
  email: string | null;
  facebook: string | null;
  full_name: string | null;
  id: number;
  instagram: string | null;
  is_female: boolean | null;
  is_pro: boolean | null;
  is_trainer: boolean | null;
  location: string | null;
  phone: string | null;
  price: number | null;
  slug: string | null;
  specializations: string | null;
  user_id: string | null;
  work_online: boolean | null;
};
